name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  check:
    env:
      API_KEY: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run lint
      - run: bun run fmt

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          target: bun-test
          tags: litefs-fts-demo:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - run: docker run --rm litefs-fts-demo:test bun test
